### ISSUE TITLE
Add possibility to configure more than one interface per host

### ISSUE THREAD

**Issue by cmeissner** [theforeman/foreman-ansible-modules#871] opened 2020-07-14 08:12 UTC
##### SUMMARY

We manage (create/delete/configure) hosts via ansible module what works fine for us. But now we need a host which provides two nics with two different subnets aligned to.
As we see in the documentation of the ansible host module (link) there are only single parameter subnet, subnet6 and domain which we assume that these configure the nic.

##### ISSUE TYPE
 
It would be great if we'll be able to manage all nics of a host. Maybe convert `subnet`, `subnet6 and `domain` into list or dict object to manage more than one interface at all.
A dict can be a better choice to address interfaces by name.

**Comment by cmeissner** [comment] 2020-07-14 08:27
As described in [API v2 documentation](https://theforeman.org/api/2.0/apidoc/v2/hosts/create.html) for creating a host. there is an `interfaces` array. This should be addressed by the ansible module to manage multiple interfaces i guess.

**Comment by evgeni** [comment] 2020-07-21 14:49
I think that's an duplicate of https://github.com/theforeman/foreman-ansible-modules/issues/757, which we are planning to address soon. Would you agree?

**Comment by cmeissner** [comment] 2020-07-21 15:01
Agreed! Is there a valid time schedule already or should we implement a workaround for a while?

**Comment by evgeni** [comment] 2020-07-21 15:08
There is no schedule, @Fobhep tried it in https://github.com/theforeman/foreman-ansible-modules/pull/792 but had some issues with it.

Best is probably to have a workaround for now :(

**Closed** 2020-07-21 15:08 UTC
Labels: duplicate, waiting on contributor
