### ISSUE TITLE
foreman_compute_resource module prints provider_params password subelement

### ISSUE THREAD

**Issue by bagasse** [theforeman/foreman-ansible-modules#592] opened 2019-11-14 14:26 UTC
##### SUMMARY

despite `password=dict(no_log=True)`  subelement in `provider_params`, foreman_compute_resource module leaks password field in task output

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/lyra/app-root/src/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Comment by mdellweg** [comment] 2019-11-14 16:54
This is a duplicate of #491

**Comment by evgeni** [comment] 2019-11-15 14:10
@bagasse could you please check the linked issue (and the ansible issues linked from there), if they properly describe your problem, we probably should add that as an "known issue" to the readme.

**Comment by bagasse** [comment] 2019-11-18 12:35
It seems that as stated in ansible/ansible#62642, it is related to loop, I was not able to reproduce this behavior:
* With loop, it print password field
* Without loop (and ansible in verbose mode to print attribute changes), it don't print password.

So as you stated, @evgeni, maybe we should add a "known issues" to our readme and add this to it.

**Comment by evgeni** [comment] 2019-11-19 14:59
#597 is merged, closing this

**Closed by evgeni** 2019-11-19 14:59 UTC
Labels: bug, duplicate, triaged
