### ISSUE TITLE
foreman_subnet won't add created domain

### ISSUE THREAD

**Issue by csproud** [theforeman/foreman-ansible-modules#821] opened 2020-05-21 08:44 UTC
##### SUMMARY
The Foreman_subnet.py set of tasks will not add my domain to my subnet, citing "no data found for <domain-name>" even though the domain exists in the GUI

The domain has been created in a previous step and even says a host is part of it. I have also used the same python module to add another domain to another subnet, though this domain was part of the DNS setup of the foreman server.

The only thing i can think of, is that the python script is doing a DNS lookup and failing?

Hammer is able to complete the add without an issue.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
2.9.1

##### KATELLO/FOREMAN VERSION
3.11/1.21.4

##### APYPIE VERSION
0.2.1

##### STEPS TO REPRODUCE
Try to create subnet, add domain

##### EXPECTED RESULTS
it creates the subnet and adds the domain

##### ACTUAL RESULTS
Just says "No data found for <domain-name>

**Comment by evgeni** [comment] 2020-05-22 13:15
can you please show us the playbook you've been using? and the full output of the module.

I'm rather sure this works in general, but might fail for you because of a missing organization or something like this. Having playbook would help debugging this.

And btw, no, there are no lookups involved.

**Comment by evgeni** [comment] 2020-06-30 11:26
Hey @csproud, could you please provide some steps to reproduce this issue? As written, it works in general, so we'd be interested to see why it does not in your case.

**Comment by evgeni** [comment] 2020-08-17 07:07
Hey @csproud I am closing this issue as "invalid" as we cannot reproduce it. If you still face the issue, please re-open it with more data.

**Closed by evgeni** 2020-08-17 07:07 UTC
Labels: triaged, user support
