### ISSUE TITLE
Found too many results while searching for domains with some.domain.com

### ISSUE THREAD

**Issue by rht-jbittner** [theforeman/foreman-ansible-modules#683] opened 2020-01-21 17:39 UTC
##### SUMMARY
In our Satellite we have some third level and forth level domains like:

- us.domain.com
- ny.us.domain.com
- orl.us.domain.com

If I do:

- name: Create subnet
  foreman_subnet:
    name: "US office subnet - 192.168.0.0"
    description: "us.domain.com"
    network: "192.168.0.0"
    mask: "255.255.255.0"
    gateway: "192.168.0.1"
    boot_mode: "Static"
    dhcp_proxy: "someproxy.domain.com"
    dns_proxy: "someproxy.domain.com"
    mtu: 1500
    domains:
       - "us.domain.com"
    organizations: "someorg"
    locations: "US"
    state: present

It fails and returns:
Found too many (3) results while searching for domains with us.domain.com"

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.8
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.12.0.29-1.el7sat.noarch
foreman-1.22.0.33-1.el7sat.noarch
```

##### APYPIE VERSION

```
Metadata-Version: 1.1
Version: 0.2.0
```

##### STEPS TO REPRODUCE

Set Foreman/Satellite with domains like:

- us.domain.com
- ny.us.domain.com
- orl.us.domain.com

Run code bellow.

```yaml
- name: Create subnet
  foreman_subnet:
    name: "US office subnet - 192.168.0.0"
    description: "us.domain.com"
    network: "192.168.0.0"
    mask: "255.255.255.0"
    gateway: "192.168.0.1"
    boot_mode: "Static"
    dhcp_proxy: "someproxy.domain.com"
    dns_proxy: "someproxy.domain.com"
    mtu: 1500
    domains:
       - "us.domain.com"
    organizations: "someorg"
    locations: "US"
    state: present
```

##### EXPECTED RESULTS

Configured subnet with right domain

##### ACTUAL RESULTS

```
Found too many (3) results while searching for domains with us.domain.com"

```

**Comment by evgeni** [comment] 2020-01-22 09:50
Hey, I tried to reproduce this, and couldn't with the latest `master`. Which version of foreman-ansible-modules are you running?

**Comment by evgeni** [comment] 2020-01-22 09:53
Ah, I can repro with the latest 0.4.0 release.

**Comment by evgeni** [comment] 2020-01-22 09:58
The following patch should fix it for you:

```patch
diff --git plugins/modules/foreman_subnet.py plugins/modules/foreman_subnet.py
index 46e8e5f..ea7a68a 100644
--- plugins/modules/foreman_subnet.py
+++ plugins/modules/foreman_subnet.py
@@ -252,7 +252,7 @@ def main():
             entity_dict['mask'] = str(IPNetwork(u'%s/%s' % (entity_dict['network'], entity_dict['cidr'])).netmask)
 
         if 'domains' in entity_dict:
-            entity_dict['domains'] = module.find_resources('domains', entity_dict['domains'], thin=True)
+            entity_dict['domains'] = module.find_resources_by_name('domains', entity_dict['domains'], thin=True)
 
         for feature in ('dhcp_proxy', 'httpboot_proxy', 'tftp_proxy', 'discovery_proxy', 'dns_proxy', 'template_proxy'):
             if feature in entity_dict:
```

As this is fixed (differently) in `master`, I wonder if this should get a 0.4.1 release or if `master` being fixed and the fix landing in 0.5.0 (whenever that will come) is sufficient?

**Comment by evgeni** [comment] 2020-01-22 09:59
What does @theforeman/ansible-modules think?

**Comment by mdellweg** [comment] 2020-01-22 10:06
I'm fine with 0.4.1. That is what we have reserved the patch level in the version for...

**Comment by mdellweg** [comment] 2020-01-22 10:07
Also the fix should ideally be verified by the original poster.
I guess with the big change merged only recently, we are not ready for 0.5.0.

**Comment by evgeni** [comment] 2020-01-22 10:29
I've opened https://github.com/theforeman/foreman-ansible-modules/pull/685 with the fix (and fixture updates). Waiting on @rht-jbittner then :)

**Comment by rht-jbittner** [comment] 2020-01-23 09:21
@evgeni I can confirm that your code change fixed my problem. Thank you.

**Comment by evgeni** [comment] 2020-01-23 09:32
Thanks!

**Comment by mdellweg** [comment] 2020-01-23 09:42
Closing manually, because this won't be merged to master.

**Closed by mdellweg** 2020-01-23 09:42 UTC
Labels: bug, triaged
